name: dart_application_1
description: An absolute bare-bones web app.

environment:
  sdk: '>=2.10.0 <3.0.0'

dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  pedantic: ^1.9.0
dependencies:
  color: ^2.0.2
